//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KolikSoftware.Eee.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KolikSoftware.Eee.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ApplicationBig {
            get {
                object obj = ResourceManager.GetObject("ApplicationBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AwayMode {
            get {
                object obj = ResourceManager.GetObject("AwayMode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AwayModeBig {
            get {
                object obj = ResourceManager.GetObject("AwayModeBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon AwayModeIco {
            get {
                object obj = ResourceManager.GetObject("AwayModeIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connect {
            get {
                object obj = ResourceManager.GetObject("Connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectBig {
            get {
                object obj = ResourceManager.GetObject("ConnectBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectionProblems {
            get {
                object obj = ResourceManager.GetObject("ConnectionProblems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectionProblemsBig {
            get {
                object obj = ResourceManager.GetObject("ConnectionProblemsBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Download {
            get {
                object obj = ResourceManager.GetObject("Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownloadBig {
            get {
                object obj = ResourceManager.GetObject("DownloadBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (empty).
        /// </summary>
        internal static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ErrorBig {
            get {
                object obj = ResourceManager.GetObject("ErrorBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExternalUser {
            get {
                object obj = ResourceManager.GetObject("ExternalUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Feedback {
            get {
                object obj = ResourceManager.GetObject("Feedback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FeedbackBig {
            get {
                object obj = ResourceManager.GetObject("FeedbackBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Follow {
            get {
                object obj = ResourceManager.GetObject("Follow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Forward {
            get {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap History {
            get {
                object obj = ResourceManager.GetObject("History", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HistoryDayLeft {
            get {
                object obj = ResourceManager.GetObject("HistoryDayLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HistoryDayRight {
            get {
                object obj = ResourceManager.GetObject("HistoryDayRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HistoryMonthLeft {
            get {
                object obj = ResourceManager.GetObject("HistoryMonthLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HistoryMonthRight {
            get {
                object obj = ResourceManager.GetObject("HistoryMonthRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.eeechat.net.
        /// </summary>
        internal static string HomePageUrl {
            get {
                return ResourceManager.GetString("HomePageUrl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Ignore {
            get {
                object obj = ResourceManager.GetObject("Ignore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Jabber {
            get {
                object obj = ResourceManager.GetObject("Jabber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mail {
            get {
                object obj = ResourceManager.GetObject("Mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Media {
            get {
                object obj = ResourceManager.GetObject("Media", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///			&lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///				&lt;xsl:variable name=&quot;bgColor&quot;&gt;
        ///					&lt;xsl:if test=&quot;eee:MessageNo mod 2 = 0&quot;&gt;#FFFFFF&lt;/xsl:if&gt;
        ///					&lt;xsl:if test=&quot;eee:MessageNo mod 2 = 1&quot;&gt;#EFEFEF&lt;/xsl:if&gt;
        ///				&lt;/xsl:variable&gt;
        ///
        ///                &lt;message messageId=&quot;{ee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate1 {
            get {
                return ResourceManager.GetString("MessageTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///			&lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///				&lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///                    &lt;div style=&quot;font-family:Verdana; font-size:11px; padding-top: 2px; padding-bottom: 2px;&quot;&gt;
        ///                        &lt;div style=&quot;background-color:#E7F3F1;&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate2 {
            get {
                return ResourceManager.GetString("MessageTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///			&lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///				&lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///					&lt;div style=&quot;font-family:Arial; font-size:12px; padding-top: 3px; padding-bottom: 3px; padding-left: 2px; padding-right: 2px;&quot;&gt;
        ///						&lt;div style=&quot;border-style: none none dot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate3 {
            get {
                return ResourceManager.GetString("MessageTemplate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///        &lt;root&gt;
        ///            &lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///                &lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///                    &lt;div style=&quot;font-family:Arial; font-size:0.7em; padding-top: 5px; padding-bottom: 15px;&quot;&gt;
        ///                        &lt;div style=&quot;colo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate4 {
            get {
                return ResourceManager.GetString("MessageTemplate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///			&lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///				&lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///					&lt;div style=&quot;font-family:Lucida Sans; font-size:10px; padding-top: 5px; padding-bottom: 15px;&quot;&gt;
        ///						&lt;div style=&quot;color:#F0F0F0; height: 10px; float:left; border: 1px #{eee: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate5 {
            get {
                return ResourceManager.GetString("MessageTemplate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///			&lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///                &lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///                    &lt;div style=&quot;font-family:Lucida Sans; font-size:10px; padding-top: 5px; padding-bottom: 15px;&quot;&gt;
        ///                        &lt;div style=&quot;color:#F0F0F0; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate6 {
            get {
                return ResourceManager.GetString("MessageTemplate6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///            &lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///                &lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///                    &lt;div style=&quot;font-family:Lucida Sans; font-size:10px; padding-top: 5px; padding-bottom: 15px;&quot;&gt;
        ///                        &lt;div style=&quot;color [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate7 {
            get {
                return ResourceManager.GetString("MessageTemplate7", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NewAccount {
            get {
                object obj = ResourceManager.GetObject("NewAccount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewAccountBig {
            get {
                object obj = ResourceManager.GetObject("NewAccountBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Notification {
            get {
                object obj = ResourceManager.GetObject("Notification", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon NotificationIco {
            get {
                object obj = ResourceManager.GetObject("NotificationIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptionsAdvanced {
            get {
                object obj = ResourceManager.GetObject("OptionsAdvanced", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptionsConnection {
            get {
                object obj = ResourceManager.GetObject("OptionsConnection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptionsLayout {
            get {
                object obj = ResourceManager.GetObject("OptionsLayout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reply {
            get {
                object obj = ResourceManager.GetObject("Reply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Smilie {
            get {
                object obj = ResourceManager.GetObject("Smilie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopIgnoring {
            get {
                object obj = ResourceManager.GetObject("StopIgnoring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StretchToggle {
            get {
                object obj = ResourceManager.GetObject("StretchToggle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Updates {
            get {
                object obj = ResourceManager.GetObject("Updates", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpdatesBig {
            get {
                object obj = ResourceManager.GetObject("UpdatesBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Upload {
            get {
                object obj = ResourceManager.GetObject("Upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UploadBig {
            get {
                object obj = ResourceManager.GetObject("UploadBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Url {
            get {
                object obj = ResourceManager.GetObject("Url", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VolumeDown {
            get {
                object obj = ResourceManager.GetObject("VolumeDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VolumeUp {
            get {
                object obj = ResourceManager.GetObject("VolumeUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
