//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KolikSoftware.Webeee.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KolikSoftware.Webeee.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///			&lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///				&lt;xsl:variable name=&quot;bgColor&quot;&gt;
        ///					&lt;xsl:if test=&quot;eee:MessageNo mod 2 = 0&quot;&gt;#FFFFFF&lt;/xsl:if&gt;
        ///					&lt;xsl:if test=&quot;eee:MessageNo mod 2 = 1&quot;&gt;#EFEFEF&lt;/xsl:if&gt;
        ///				&lt;/xsl:variable&gt;
        ///
        ///                &lt;message messageId=&quot;{ee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate1 {
            get {
                return ResourceManager.GetString("MessageTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///			&lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///				&lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///                    &lt;div style=&quot;font-family:Verdana; font-size:11px; padding-top: 2px; padding-bottom: 2px;&quot;&gt;
        ///                        &lt;div style=&quot;background-color:#E7F3F1;&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate2 {
            get {
                return ResourceManager.GetString("MessageTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///			&lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///				&lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///					&lt;div style=&quot;font-family:Arial; font-size:12px; padding-top: 3px; padding-bottom: 3px; padding-left: 2px; padding-right: 2px;&quot;&gt;
        ///						&lt;div style=&quot;border-style: none none dot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate3 {
            get {
                return ResourceManager.GetString("MessageTemplate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///        &lt;root&gt;
        ///            &lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///                &lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///                    &lt;div style=&quot;font-family:Lucida Sans; font-size:10px; padding-top: 5px; padding-bottom: 15px;&quot;&gt;
        ///                        &lt;div style= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate4 {
            get {
                return ResourceManager.GetString("MessageTemplate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///			&lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///				&lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///					&lt;div style=&quot;font-family:Lucida Sans; font-size:10px; padding-top: 5px; padding-bottom: 15px;&quot;&gt;
        ///						&lt;div style=&quot;color:#F0F0F0; height: 10px; float:left; border: 1px #{eee: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate5 {
            get {
                return ResourceManager.GetString("MessageTemplate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///			&lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///                &lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///                    &lt;div style=&quot;font-family:Lucida Sans; font-size:10px; padding-top: 5px; padding-bottom: 15px;&quot;&gt;
        ///                        &lt;div style=&quot;color:#F0F0F0; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate6 {
            get {
                return ResourceManager.GetString("MessageTemplate6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet	version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:eee=&quot;http://tempuri.org/EeeDataSet.xsd&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; /&gt;
        ///
        ///	&lt;xsl:template match=&quot;/eee:EeeDataSet&quot;&gt;
        ///		&lt;root&gt;
        ///            &lt;xsl:for-each select=&quot;eee:Message&quot;&gt;
        ///                &lt;message messageId=&quot;{eee:MessageID}&quot;&gt;
        ///                    &lt;div style=&quot;font-family:Lucida Sans; font-size:10px; padding-top: 5px; padding-bottom: 15px;&quot;&gt;
        ///                        &lt;div style=&quot;color [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageTemplate7 {
            get {
                return ResourceManager.GetString("MessageTemplate7", resourceCulture);
            }
        }
    }
}
